### ISSUE TITLE
First Priority List (from Parnell)

### ISSUE THREAD

**Issue by Athospd** [hamilton-institute/hamiltonCovid19#2]
# Overall work plan
- Attend bi-weekly meetings of research group (every other Wednesday at 11am Irish time)
- Ensure that hamilton.ie/covid19 is working and that all pages/apps are running
- Ensure that all Shiny apps have a consistent appearance
- Ensure that minor updates to the Shiny apps can be implemented without breaking other parts
- Ensure that new blog posts added to the page don’t break any other parts of the website

# Work items in order of priority
- [x] Create secure sign in area on web page. Provide a simple Shiny app that shows how the private area can be used (#7)
- [ ] Fix themes (i.e. fonts, colours, sizes) of all apps to be the same and match the overall distill theme (#8)
- [ ] Tidy up the code of the main dashboard to remove unused parts and unify the structure to be more readable
- [ ] Fix bugs in main dashboard (separate list, likely to be periodically updated) - see below
- [ ] Add the Maynooth University logo to the footer of the web page
- [ ] Fix iframe heights on all apps in the web page
- [ ] Update about.html page to look nicer (possibly include pictures of group?)
- [ ] Add Curso-R into the about page (and a link to your website)
- [ ] Remove titles from all apps (titles are already shown at top of web page)

# Current dashboard bugs:
- Fix weird time behaviour in e.g. Ireland vs World diagnoses boxes (always 1 hour apart?)
- Add a title: “14-day cases per 100,000 residents” to the map on the main screen
- Fix legend on map page - NA in wrong place
- Remove axis labels from the legend on the ‘graphs’ tab
- Fix the play bar in the Animations tab to start at a reasonable point (1st of previous month?)
- Remove the loading bar from between the animation frames
- Fix height of map on right hand side of main page so that it is consistently the same height as the boxes
- Change country names in data tables (and plots?) to no longer have underscores between them, e.g. South_Africa
- (Harder) perhaps put a dropdown box in the data tables on the front page to switch between cases, deaths, 14-days per 100k residents, etc
- (Possibly one for me - I would like the top row of the dashboard to show the current number and/capacity of people in Irish hospitals and ICU) I think that information is available here: [ https://covid19ireland-geohive.hub.arcgis.com/search?groupIds=7e244cadac05461fb60b287a37b5ed2b]()
